public class Constants {
    
    public static String Booked = 'Booked';
    public static String Room_Allotted = 'Room Allotted';
    public static String Student = 'Student';
    public static String Applicant = 'Applicant';
    public static String StudentPortalProfile = 'Student Portal Profile';
    public static String NonTeachingStaffProfile = 'Non Teaching Profile';
    public static Integer baseIndex = 0;
    public static String NonTeachingStaff = 'Non-Teaching Staff';
    public static String TeachingStaff = 'Professor';
    public static String ApplicantProfile = 'Applicant Profile';
    public static String StudentProfile = 'Student Profile';

}