public class WhatsappNotification_FeeReminder {
    /*@InvocableMethod(label='Send WhatsApp Notifications for Fee Reminder' description='Send notifications via WhatsApp for fee reminders')
    public static void sendFeeReminderNotifications(List<String> recordIds) {
        if (recordIds != null && !recordIds.isEmpty()) {
            // Initiate the batch job for the given record IDs
            StudentFeeNotificationBatch batch = new StudentFeeNotificationBatch();
            Database.executeBatch(batch, 50); // Specify batch size (e.g., 50)
        } else {
            System.debug('RecordIds List is Empty');
        }
    }*/
}